Origin/feature/problems benefits
dmitrysdevfs/hell-en-project pull request #28
Opened 2022-05-14 17:03 UTC by Miradzyapko

2022-05-14 22:20 UTC, dmitrysdevfs commented on src/sass/layout/_problems.scss
> +    background-repeat: no-repeat; background-position: center; background-size:cover;
Спробуй задати фон на секцію градієнтом наступним чином:

background-image: linear-gradient(
  to bottom,
  var(--add-textcolor) 80%,
  #ffffff 80%,
);

СВГ-зображення фону не потрібне.

2022-05-14 22:28 UTC, dmitrysdevfs commented on src/sass/layout/_problems.scss
> +   display: length;
Для чого цей дісплей?

2022-05-14 22:31 UTC, dmitrysdevfs commented on src/sass/layout/_problems.scss
> + @media screen and (min-width: 768px)
Тут щось наплутано:

Медіа-правило {
element {
  властивість
  }
}

2022-05-14 22:34 UTC, dmitrysdevfs commented on src/sass/layout/_problems.scss
> +    @media screen and (min-width: 480px)
немає елементу до якого застосовуються падінги. 
Також правильніше медіа правила писати від меньшого вьюпорта до більшого

2022-05-14 22:35 UTC, dmitrysdevfs commented on src/sass/layout/_problems.scss
> +    @media screen and (min-width: 1366px)
Точка перелому вчора змінила ментор, тепер для десктопів вона 1680px

2022-05-14 22:36 UTC, dmitrysdevfs commented on src/sass/layout/_problems.scss
> +     @media screen and (min-width: 1366px)
Неправильна точка перелому

2022-05-14 22:46 UTC, dmitrysdevfs requested changes
Треба виправляти, деякі правила не будуть працювати, тому що вказані елементи, до яких вони застосовуються. Залишилось мало часу, якщо будуе складно. потрібно повідомити завчасно.

2022-05-14 23:56 UTC, Miradzyapko commented on src/sass/layout/_problems.scss
> +    background-repeat: no-repeat; background-position: center; background-size:cover;
вже задала я помітила помилку

2022-05-15 15:07 UTC, dmitrysdevfs approved these changes

2022-05-15 15:08 UTC, merged